services:

    Shopping\FeatureFlagBundle\Provider\FeatureFlagInterface: '@Shopping\FeatureFlagBundle\Provider\ChainProvider'
    Shopping\FeatureFlagBundle\Provider\ChainProvider: ~

    Shopping\FeatureFlagBundle\Provider\DotEnvProvider:
        arguments:
            $isEnabled: ''
        tags:
            - { name: featureFlag.provider }

    Shopping\FeatureFlagBundle\Provider\CookieProvider:
        arguments:
            $requestStack: '@request_stack'
            $isEnabled: ''
            $values: []
        tags:
            - { name: featureFlag.provider }

    Shopping\FeatureFlagBundle\Provider\UserAgentProvider:
        arguments:
            $requestStack: '@request_stack'
            $isEnabled: ''
            $values: []
        tags:
            - { name: featureFlag.provider }


    Shopping\FeatureFlagBundle\EventListener\FeatureFlagAnnotationListener:
        arguments:
            $reader: '@annotations.reader'
            $requestStack: '@request_stack'
            $featureFlag: '@Shopping\FeatureFlagBundle\Provider\FeatureFlagInterface'
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    Shopping\FeatureFlagBundle\Twig\FeatureFlagExtension:
        arguments:
            $featureFlag: '@Shopping\FeatureFlagBundle\Provider\FeatureFlagInterface'
        tags:
            - { name: twig.extension }